name: "G-PST Open Tools Portal Builder"
description: "Validates opentools source data and builds the portal website"
author: "Kapil Duwadi and Gord Stephen"

inputs:
  datapath:
    description: "Path to source data folder. Defaults to 'data'."
    required: false
    default: "data"
  sitepath:
    description: "Path to folder in which to generate site. Defaults to 'site'."
    required: false
    default: "site"
  errorpath:
    description: "Path to file in which to write details of any parse errors. Defaults to 'errormessage.md'."
    required: false
    default: "errormessage.md"
  baseurl:
    description: "URL prefix to be applied to links within the generated site."
    required: false
    default: "/"

runs:
  using: docker
  image: "Dockerfile"
